import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ posts }) {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>My Pets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Mascotas</h1>
          <div className={styles.rows}>
          <Link href={{
            pathname: '/editar',
          }}>
          <button className={styles.button23} role="button">Editar mascotas</button>
          </Link>
          <Link href={{
            pathname: '/crear',
          }}>
          <button className={styles.button23} role="button">Crear mascota</button>
          </Link>
          <Link href={{
            pathname: '/eliminar',
          }}>
          <button className={styles.button23} role="button">Eliminar mascota</button>
          </Link>
          
          </div>


        </div>
        <h2> Mis mascotas </h2>

        <div className={styles.grid} >

          {posts.map((post) => (
            <div className={styles.card} onClick={(e) => {
              
                router.push({
                  pathname: '/pet',
                  query: { name: post.name, age: post.age, image_pet: post.image_pet, description: post.description },
                })
              
            }} key={post.id}  >

              <div className={styles.imagecard}>
                <div>
                  <h2 className={styles.name} >{post.name}</h2>

                  <p className={styles.age}>{post.age} Años</p>

                  

                </div>


                <img src={post.image_pet} alt="image pet" className={styles.imagepet} />

              </div>
            </div>

          ))
          }
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('https://nodejs-mysql-restapi-pets-production.up.railway.app/api/pets')
  const posts = await res.json()

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      posts,
    },
  }
}