import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link'
import axios from 'axios'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  const [data, setData] = useState([])

  const response = async () => {
    const res = await axios.get('https://nodejs-mysql-restapi-pets-production.up.railway.app/api/pets')
    setData(res.data)
    console.log(res.data)
  } 

    useEffect(() => {
      response()
    }, [])


  return (
    <>
      <Head>
        <title>My Pets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Mascotas</h1>
          <div className={styles.rows}>
          <Link href={{
            pathname: '/editar',
          }}>
          <button className={styles.button23} role="button">Editar mascotas</button>
          </Link>
          <Link href={{
            pathname: '/crear',
          }}>
          <button className={styles.button23} role="button">Crear mascota</button>
          </Link>
          <Link href={{
            pathname: '/eliminar',
          }}>
          <button className={styles.button23} role="button">Eliminar mascota</button>
          </Link>
          
          </div>


        </div>
        <h2> Mis mascotas </h2>

        <div className={styles.grid} >

          {data && Object.keys(data).map((key) => {
            
            return (
              <div className={styles.card} onClick={(e) => {
              
                router.push({
                  pathname: '/pet',
                  query: { name: data[key].name, age: data[key].age, image_pet: data[key].image_pet, description: data[key].description },
                })
              
            }} key={key.id}  >

              <div className={styles.imagecard}>
                <div>
                  <h2 className={styles.name} >{data[key].name}</h2>

                  <p className={styles.age}>{data[key].age} Años</p>

                  

                </div>


                <img src={data[key].image_pet} alt="image pet" className={styles.imagepet} />

              </div>
            </div>
            )
          })
          }
        </div>
      </main>
    </>
  )
}

