import { Updock } from "@next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import styles from "../styles/Pet.module.css";
import { useState } from "react";
export default function Pet() {
    const router = useRouter()
    const { name, age, image_pet,description } = router.query
    const handelClick = (e) => {
        router.push({
            pathname: '/',
        })
    }
    return (
        <div>
            <Head>
                <title>About {name}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href={image_pet} className={styles.icon} />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <div onClick={handelClick}>
                    <h1>&larr; {name}</h1>
                    </div>
                  
                    <p>{name} is {age} years old</p>
                    
                </div>
                <div className={styles.content }>
                <h2>{description}</h2>
                <img src={image_pet} alt="image pet" className={styles.imagepet} />
                </div>
              
            </main>

        </div>
    )
}